### ISSUE TITLE
HW part 1

### ISSUE THREAD

**Issue by jkunzethz** [sta426hs2016/material#1]
https://github.com/jkunzethz/sta426sample/blob/master/README.md

**Comment by megpay** [comment]
https://github.com/payne76/crispy-octo-chainsaw/blob/master/README.md

**Comment by khembach** [comment]
https://github.com/khembach/STA426/blob/master/README.md

**Comment by kli8996** [comment]
https://github.com/kli8996/STA426/blob/master/README.md

**Comment by ellereve** [comment]
https://github.com/ellereve/Pub

**Comment by laurapi** [comment]
[Laura Piñeiro repo](https://github.com/laurapi/homework1/blob/master/README.mdl)

**Comment by gasimomitis** [comment]
https://github.com/gasimomitis/gasim_STA426hs2016/blob/master/README.md

**Comment by paulacarrio** [comment]
https://github.com/paulacarrio/STA426/blob/master/README.md

**Comment by leewayleaf** [comment]
https://github.com/leewayleaf/hello-world

**Comment by mbizzo** [comment]
https://github.com/mbizzo/Ex1/blob/master/README.md

**Comment by bunnech** [comment]
https://github.com/bunnech/Statistical-Analysis-UZH.git

**Comment by mfeiche** [comment]
https://github.com/mfeiche/STA-426-HS16/blob/master/README.md
